import { AuthUser } from "@/types/AuthUser";
import { User } from "@/types/User";
import { Task } from "@/types/Task";
import { MileStone } from "@/types/MileStone";
import { ParticipationRequest } from "@/types/ParticipationRequest";
import { Schedule } from "@/types/Schedule";
import { Channel } from "@/types/Channel";
export interface Project {
  id: string;
  title: string;
  description: string;
  status: string;
  visibility: string;
  start_date: string;
  end_date: string;
  team_size: number;
  project_type: string;
  tags: string[];
  location: string;
  github_url: string;
  completed_at: string;
  owner: AuthUser;
  members: {
    user: User;
    is_leader: boolean;
    is_manager: boolean;
    joined_at: string;
    role: string;
  }[];
  tasks: Task[];
  milestones: MileStone[];
  participation_requests: ParticipationRequest[];
  schedules: Schedule[];
  channels: Channel[];
  task_count: number;
  task_completed_count: number;
  milestone_count: number;
  completed_milestone_count: number;
  participation_request_count: number;
  schedule_count: number;
  channel_count: number;
  chat_count: number;
}